import React from "react";

export const styles: Record<string, React.CSSProperties> = {
  container: {
    maxWidth: 860,
    margin: "0 auto",
    padding: "24px 16px",
    fontFamily:
      "'Pretendard', 'Apple SD Gothic Neo', -apple-system, sans-serif",
    color: "#E2E8F0",
    background: "#0F172A",
    minHeight: "100vh",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 24,
    flexWrap: "wrap",
    gap: 12,
  },
  title: {
    fontSize: 22,
    fontWeight: 800,
    color: "#F8FAFC",
    margin: 0,
    letterSpacing: "-0.5px",
  },
  subtitle: {
    fontSize: 13,
    color: "#64748B",
    margin: "6px 0 0",
  },
  settingsBtn: {
    background: "#1E293B",
    color: "#94A3B8",
    border: "1px solid #334155",
    borderRadius: 8,
    padding: "8px 16px",
    fontSize: 13,
    cursor: "pointer",
    transition: "all .15s",
  },
  backBtn: {
    background: "none",
    color: "#94A3B8",
    border: "none",
    fontSize: 14,
    cursor: "pointer",
    padding: 0,
  },
  resetBtn: {
    background: "#1E293B",
    color: "#F87171",
    border: "1px solid #7F1D1D",
    borderRadius: 8,
    padding: "8px 16px",
    fontSize: 13,
    cursor: "pointer",
  },
  controlsRow: {
    display: "flex",
    gap: 16,
    marginBottom: 20,
    flexWrap: "wrap",
  },
  controlBox: {
    flex: 1,
    minWidth: 240,
    background: "#1E293B",
    borderRadius: 12,
    padding: "16px 20px",
    border: "1px solid #334155",
  },
  controlLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: "#94A3B8",
    marginBottom: 8,
    display: "block",
  },
  controlInputRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  slider: {
    flex: 1,
    accentColor: "#3B82F6",
  },
  controlValue: {
    fontSize: 14,
    fontWeight: 700,
    color: "#F8FAFC",
    whiteSpace: "nowrap",
  },
  dripRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  toggle: {
    width: 44,
    height: 24,
    borderRadius: 12,
    border: "none",
    cursor: "pointer",
    position: "relative",
    transition: "background .2s",
  },
  toggleKnob: {
    width: 20,
    height: 20,
    borderRadius: "50%",
    background: "#fff",
    position: "absolute",
    top: 2,
    transition: "transform .2s",
    boxShadow: "0 1px 3px rgba(0,0,0,.3)",
  },
  dripStatus: {
    fontSize: 12,
    fontWeight: 500,
  },
  shareGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(150px, 1fr))",
    gap: 10,
    marginBottom: 10,
  },
  shareCard: {
    background: "#1E293B",
    borderRadius: 10,
    padding: "12px 14px",
    border: "1px solid #334155",
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    display: "inline-block",
  },
  shareTicker: {
    fontSize: 14,
    fontWeight: 800,
    color: "#F8FAFC",
  },
  sharePrice: {
    fontSize: 11,
    color: "#64748B",
    marginLeft: "auto",
  },
  krwSmall: {
    fontSize: 10,
    color: "#536878",
    marginBottom: 6,
    paddingLeft: 16,
  },
  shareInputRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  shareLabel: {
    fontSize: 12,
    color: "#94A3B8",
  },
  pmBtn: {
    width: 28,
    height: 28,
    borderRadius: 6,
    background: "#334155",
    color: "#E2E8F0",
    border: "none",
    fontSize: 16,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
  },
  shareInput: {
    width: 42,
    textAlign: "center",
    background: "#0F172A",
    border: "1px solid #475569",
    borderRadius: 6,
    color: "#F8FAFC",
    fontSize: 14,
    fontWeight: 700,
    padding: "4px 0",
  },
  shareCost: {
    fontSize: 11,
    color: "#64748B",
    marginTop: 6,
    textAlign: "right",
  },
  monthlyCostBanner: {
    textAlign: "center",
    fontSize: 14,
    color: "#94A3B8",
    background: "#1E293B",
    borderRadius: 8,
    padding: "10px 12px",
    marginBottom: 20,
    border: "1px solid #334155",
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))",
    gap: 12,
    marginBottom: 16,
  },
  summaryCard: {
    background: "#1E293B",
    borderRadius: 12,
    padding: "16px 18px",
    border: "1px solid #334155",
  },
  summaryLabel: {
    fontSize: 12,
    color: "#64748B",
    marginBottom: 6,
    fontWeight: 500,
  },
  priceBar: {
    background: "#1E293B",
    borderRadius: 10,
    padding: "12px 16px",
    marginBottom: 20,
    border: "1px solid #334155",
  },
  priceBarLabel: {
    fontSize: 12,
    color: "#64748B",
    fontWeight: 600,
    marginBottom: 8,
    display: "block",
  },
  priceBarChips: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
  },
  priceChip: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "#0F172A",
    borderRadius: 6,
    padding: "6px 10px",
    border: "1px solid #334155",
  },
  chartBox: {
    background: "#1E293B",
    borderRadius: 14,
    padding: "20px 16px 12px",
    marginBottom: 20,
    border: "1px solid #334155",
  },
  chartTitle: {
    fontSize: 15,
    fontWeight: 700,
    color: "#CBD5E1",
    margin: "0 0 12px 4px",
  },
  settingsGrid: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    marginTop: 12,
  },
  settingsCard: {
    background: "#1E293B",
    borderRadius: 12,
    padding: "18px 20px",
    border: "1px solid #334155",
  },
  settingsCardHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 14,
  },
  tickerBadge: {
    color: "#fff",
    fontWeight: 800,
    fontSize: 12,
    padding: "3px 10px",
    borderRadius: 6,
  },
  etfName: {
    fontSize: 13,
    color: "#94A3B8",
  },
  settingsFields5: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))",
    gap: 12,
  },
  fieldGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  fieldLabel: {
    fontSize: 11,
    color: "#64748B",
    fontWeight: 600,
  },
  input: {
    background: "#0F172A",
    border: "1px solid #475569",
    borderRadius: 8,
    color: "#F8FAFC",
    fontSize: 15,
    fontWeight: 700,
    padding: "8px 12px",
    width: "100%",
    boxSizing: "border-box",
  },
  krwHint: {
    fontSize: 11,
    color: "#536878",
    marginTop: 2,
  },
  yieldDisplay: {
    fontSize: 15,
    fontWeight: 700,
    color: "#10B981",
    padding: "8px 0",
  },
  growthNote: {
    marginTop: 20,
    padding: "14px 18px",
    background: "#0F172A",
    borderRadius: 10,
    border: "1px solid #334155",
    fontSize: 12,
    color: "#64748B",
    lineHeight: 1.7,
  },
  footer: {
    textAlign: "center",
    fontSize: 11,
    color: "#475569",
    padding: "16px 0 8px",
    lineHeight: 1.8,
  },
};
