export const DEFAULT_ETFS = [
  {
    ticker: "SCHD",
    name: "Schwab US Dividend Equity",
    price: 30.84,
    annualDiv: 1.08,
    yield: 3.5,
    freq: "quarterly",
    annualGrowth: 10.0,
    color: "#3B82F6",
  },
  {
    ticker: "JEPQ",
    name: "JPMorgan Nasdaq Equity Premium Income",
    price: 56.57,
    annualDiv: 6.16,
    yield: 10.89,
    freq: "monthly",
    annualGrowth: 3.0,
    color: "#F59E0B",
  },
  {
    ticker: "JEPI",
    name: "JPMorgan Equity Premium Income",
    price: 57.09,
    annualDiv: 4.76,
    yield: 8.34,
    freq: "monthly",
    annualGrowth: 2.0,
    color: "#10B981",
  },
  {
    ticker: "DGRO",
    name: "iShares Core Dividend Growth",
    price: 71.56,
    annualDiv: 1.45,
    yield: 2.03,
    freq: "quarterly",
    annualGrowth: 9.0,
    color: "#8B5CF6",
  },
  {
    ticker: "VYM",
    name: "Vanguard High Dividend Yield",
    price: 148.71,
    annualDiv: 3.5,
    yield: 2.35,
    freq: "quarterly",
    annualGrowth: 7.5,
    color: "#EF4444",
  },
];

export const DEFAULT_FX = 1400;
